import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Copy, Check, RotateCcw, Download, Palette, Sparkles } from "lucide-react";

interface ColorConfig {
  name: string;
  label: string;
  description: string;
  hue: number;
  saturation: number;
  lightness: number;
}

const defaultColors: ColorConfig[] = [
  { name: "base", label: "Base Surface", description: "Main background", hue: 214, saturation: 20, lightness: 91 },
  { name: "primary", label: "Primary Accent", description: "Buttons & links", hue: 216, saturation: 45, lightness: 47 },
  { name: "success", label: "Success", description: "Positive states", hue: 145, saturation: 40, lightness: 46 },
  { name: "warning", label: "Warning", description: "Alerts & caution", hue: 28, saturation: 55, lightness: 64 },
  { name: "error", label: "Error", description: "Error states", hue: 0, saturation: 55, lightness: 57 },
];

const ThemeBuilder = () => {
  const [colors, setColors] = useState<ColorConfig[]>(defaultColors);
  const [isDarkPreview, setIsDarkPreview] = useState(false);
  const [copied, setCopied] = useState(false);
  const [activeColor, setActiveColor] = useState<string>("primary");
  const [shadowIntensity, setShadowIntensity] = useState([60]);
  const [borderRadius, setBorderRadius] = useState([20]);

  const updateColor = (name: string, property: keyof ColorConfig, value: number) => {
    setColors(prev => prev.map(c => 
      c.name === name ? { ...c, [property]: value } : c
    ));
  };

  const resetColors = () => {
    setColors(defaultColors);
    setShadowIntensity([60]);
    setBorderRadius([20]);
  };

  const generateYAML = () => {
    const baseColor = colors.find(c => c.name === "base")!;
    const primaryColor = colors.find(c => c.name === "primary")!;
    const successColor = colors.find(c => c.name === "success")!;
    const warningColor = colors.find(c => c.name === "warning")!;
    const errorColor = colors.find(c => c.name === "error")!;

    return `# Custom Neumorphic Theme - Generated by Theme Builder
# Generated: ${new Date().toISOString().split('T')[0]}

Full Neumorphic Custom:
  # Base Surface
  neumorphic-base-hue: "${baseColor.hue}"
  neumorphic-base-saturation: "${baseColor.saturation}%"
  neumorphic-base-lightness: "${baseColor.lightness}%"
  neumorphic-base: "hsl(${baseColor.hue}, ${baseColor.saturation}%, ${baseColor.lightness}%)"
  
  # Primary Accent
  accent-primary-hue: "${primaryColor.hue}"
  accent-primary: "hsl(${primaryColor.hue}, ${primaryColor.saturation}%, ${primaryColor.lightness}%)"
  accent-primary-light: "hsl(${primaryColor.hue}, ${primaryColor.saturation + 5}%, ${primaryColor.lightness + 18}%)"
  
  # State Colors
  accent-success: "hsl(${successColor.hue}, ${successColor.saturation}%, ${successColor.lightness}%)"
  accent-warning: "hsl(${warningColor.hue}, ${warningColor.saturation}%, ${warningColor.lightness}%)"
  accent-error: "hsl(${errorColor.hue}, ${errorColor.saturation}%, ${errorColor.lightness}%)"
  
  # Shadow Intensity
  shadow-intensity: "${shadowIntensity[0] / 100}"
  
  # Border Radius
  ha-card-border-radius: "${borderRadius[0]}px"
  
  # Calculated Shadows
  shadow-convex: |
    9px 9px 16px hsla(${baseColor.hue}, ${baseColor.saturation}%, ${baseColor.lightness - 20}%, ${shadowIntensity[0] / 100}),
    -9px -9px 16px hsla(0, 0%, 100%, ${(shadowIntensity[0] / 100) * 0.8})`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateYAML());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const yaml = generateYAML();
    const blob = new Blob([yaml], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'custom_neumorphic_theme.yaml';
    a.click();
    URL.revokeObjectURL(url);
  };

  const activeColorConfig = colors.find(c => c.name === activeColor)!;
  
  // Generate preview styles
  const previewBaseColor = colors.find(c => c.name === "base")!;
  const previewPrimaryColor = colors.find(c => c.name === "primary")!;
  
  const baseHsl = `hsl(${previewBaseColor.hue}, ${previewBaseColor.saturation}%, ${isDarkPreview ? 16 : previewBaseColor.lightness}%)`;
  const primaryHsl = `hsl(${previewPrimaryColor.hue}, ${previewPrimaryColor.saturation}%, ${previewPrimaryColor.lightness}%)`;
  const shadowDark = `hsla(${previewBaseColor.hue}, ${previewBaseColor.saturation}%, ${isDarkPreview ? 6 : previewBaseColor.lightness - 20}%, ${shadowIntensity[0] / 100})`;
  const shadowLight = `hsla(0, 0%, ${isDarkPreview ? 22 : 100}%, ${(shadowIntensity[0] / 100) * 0.8})`;

  return (
    <section className="mb-16">
      <div className="text-center mb-8">
        <Badge className="badge-neumorphic mb-4 gap-2">
          <Palette className="w-4 h-4" />
          Theme Builder
        </Badge>
        <h3 className="text-3xl font-display font-bold text-primary-text mb-3">
          Создай свою тему
        </h3>
        <p className="text-secondary-text max-w-xl mx-auto">
          Настрой цвета, тени и закругления — скачай готовый YAML для Home Assistant
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {/* Controls Panel */}
        <Card className="card-neumorphic-lg overflow-visible">
          <CardHeader>
            <CardTitle className="text-lg font-medium text-primary-text flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-primary" />
              Настройки темы
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Color Selector Tabs */}
            <div className="flex flex-wrap gap-2">
              {colors.map((color) => (
                <button
                  key={color.name}
                  onClick={() => setActiveColor(color.name)}
                  className={`px-4 py-2 rounded-xl text-sm font-medium transition-all ${
                    activeColor === color.name
                      ? 'bg-primary text-white shadow-lg'
                      : 'bg-neumorphic-inset text-secondary-text hover:text-primary-text'
                  }`}
                  style={activeColor === color.name ? { 
                    backgroundColor: `hsl(${color.hue}, ${color.saturation}%, ${color.lightness}%)` 
                  } : {}}
                >
                  {color.label}
                </button>
              ))}
            </div>

            {/* Active Color Controls */}
            <div className="space-y-4 p-4 rounded-xl bg-neumorphic-inset">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-medium text-primary-text">{activeColorConfig.label}</span>
                <div 
                  className="w-10 h-10 rounded-lg shadow-lg"
                  style={{ 
                    backgroundColor: `hsl(${activeColorConfig.hue}, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%)` 
                  }}
                />
              </div>
              
              <div className="space-y-4">
                <div>
                  <div className="flex justify-between text-sm mb-2">
                    <span className="text-secondary-text">Hue</span>
                    <span className="text-primary-text font-mono">{activeColorConfig.hue}°</span>
                  </div>
                  <div className="h-3 rounded-full relative overflow-hidden"
                    style={{
                      background: `linear-gradient(to right, 
                        hsl(0, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%),
                        hsl(60, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%),
                        hsl(120, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%),
                        hsl(180, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%),
                        hsl(240, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%),
                        hsl(300, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%),
                        hsl(360, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%)
                      )`
                    }}
                  >
                    <Slider
                      value={[activeColorConfig.hue]}
                      onValueChange={([v]) => updateColor(activeColor, 'hue', v)}
                      max={360}
                      step={1}
                      className="absolute inset-0 opacity-0 cursor-pointer"
                    />
                    <div 
                      className="absolute top-1/2 -translate-y-1/2 w-4 h-4 rounded-full border-2 border-white shadow-lg pointer-events-none"
                      style={{ 
                        left: `calc(${(activeColorConfig.hue / 360) * 100}% - 8px)`,
                        backgroundColor: `hsl(${activeColorConfig.hue}, ${activeColorConfig.saturation}%, ${activeColorConfig.lightness}%)`
                      }}
                    />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between text-sm mb-2">
                    <span className="text-secondary-text">Saturation</span>
                    <span className="text-primary-text font-mono">{activeColorConfig.saturation}%</span>
                  </div>
                  <Slider
                    value={[activeColorConfig.saturation]}
                    onValueChange={([v]) => updateColor(activeColor, 'saturation', v)}
                    max={100}
                    step={1}
                    className="slider-neumorphic"
                  />
                </div>

                <div>
                  <div className="flex justify-between text-sm mb-2">
                    <span className="text-secondary-text">Lightness</span>
                    <span className="text-primary-text font-mono">{activeColorConfig.lightness}%</span>
                  </div>
                  <Slider
                    value={[activeColorConfig.lightness]}
                    onValueChange={([v]) => updateColor(activeColor, 'lightness', v)}
                    max={100}
                    step={1}
                    className="slider-neumorphic"
                  />
                </div>
              </div>
            </div>

            {/* Global Settings */}
            <div className="space-y-4">
              <div>
                <div className="flex justify-between text-sm mb-2">
                  <span className="text-secondary-text">Shadow Intensity</span>
                  <span className="text-primary-text font-mono">{shadowIntensity[0]}%</span>
                </div>
                <Slider
                  value={shadowIntensity}
                  onValueChange={setShadowIntensity}
                  max={100}
                  step={5}
                  className="slider-neumorphic"
                />
              </div>

              <div>
                <div className="flex justify-between text-sm mb-2">
                  <span className="text-secondary-text">Border Radius</span>
                  <span className="text-primary-text font-mono">{borderRadius[0]}px</span>
                </div>
                <Slider
                  value={borderRadius}
                  onValueChange={setBorderRadius}
                  min={4}
                  max={40}
                  step={2}
                  className="slider-neumorphic"
                />
              </div>
            </div>

            {/* Actions */}
            <div className="flex flex-wrap gap-3 pt-4">
              <Button onClick={resetColors} className="btn-neumorphic-secondary flex-1">
                <RotateCcw className="w-4 h-4 mr-2" />
                Сброс
              </Button>
              <Button onClick={handleCopy} className="btn-neumorphic-secondary flex-1">
                {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                {copied ? "Скопировано!" : "Копировать"}
              </Button>
              <Button onClick={handleDownload} className="btn-neumorphic-primary flex-1">
                <Download className="w-4 h-4 mr-2" />
                Скачать YAML
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Live Preview */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-primary-text">Live Preview</span>
            <div className="flex items-center gap-2">
              <span className="text-sm text-secondary-text">Dark Mode</span>
              <Switch checked={isDarkPreview} onCheckedChange={setIsDarkPreview} />
            </div>
          </div>
          
          <div 
            className="rounded-2xl p-6 transition-all duration-300"
            style={{ 
              backgroundColor: baseHsl,
              boxShadow: `12px 12px 24px ${shadowDark}, -12px -12px 24px ${shadowLight}`
            }}
          >
            {/* Preview Header */}
            <div 
              className="rounded-xl p-4 mb-4"
              style={{
                backgroundColor: baseHsl,
                boxShadow: `6px 6px 12px ${shadowDark}, -6px -6px 12px ${shadowLight}`,
                borderRadius: `${borderRadius[0]}px`
              }}
            >
              <div className="flex items-center gap-3">
                <div 
                  className="w-10 h-10 rounded-lg flex items-center justify-center"
                  style={{ backgroundColor: primaryHsl }}
                >
                  <span className="text-white text-lg">🏠</span>
                </div>
                <div>
                  <div style={{ color: isDarkPreview ? '#e5e5e5' : '#1a1a2e' }} className="font-semibold">
                    My Home
                  </div>
                  <div style={{ color: isDarkPreview ? '#888' : '#666' }} className="text-sm">
                    Dashboard Preview
                  </div>
                </div>
              </div>
            </div>

            {/* Preview Cards Grid */}
            <div className="grid grid-cols-2 gap-4">
              {[
                { icon: "💡", label: "Lights", value: "3 on" },
                { icon: "🌡️", label: "Climate", value: "22°C" },
                { icon: "🔐", label: "Security", value: "Armed" },
                { icon: "⚡", label: "Energy", value: "2.4 kW" },
              ].map((item, i) => (
                <div
                  key={i}
                  className="p-4 text-center transition-all"
                  style={{
                    backgroundColor: baseHsl,
                    boxShadow: `4px 4px 8px ${shadowDark}, -4px -4px 8px ${shadowLight}`,
                    borderRadius: `${borderRadius[0]}px`
                  }}
                >
                  <div className="text-2xl mb-2">{item.icon}</div>
                  <div 
                    className="text-xs mb-1"
                    style={{ color: isDarkPreview ? '#888' : '#666' }}
                  >
                    {item.label}
                  </div>
                  <div 
                    className="font-semibold"
                    style={{ color: isDarkPreview ? '#e5e5e5' : '#1a1a2e' }}
                  >
                    {item.value}
                  </div>
                </div>
              ))}
            </div>

            {/* Preview Button */}
            <button
              className="w-full mt-4 py-3 px-4 font-medium text-white rounded-xl transition-all"
              style={{ 
                backgroundColor: primaryHsl,
                borderRadius: `${borderRadius[0]}px`,
                boxShadow: `4px 4px 8px ${shadowDark}`
              }}
            >
              Activate Scene
            </button>
          </div>

          {/* Color Swatches */}
          <div className="flex justify-center gap-2">
            {colors.map((color) => (
              <div
                key={color.name}
                className="w-8 h-8 rounded-lg shadow-md cursor-pointer hover:scale-110 transition-transform"
                style={{ 
                  backgroundColor: `hsl(${color.hue}, ${color.saturation}%, ${color.lightness}%)` 
                }}
                onClick={() => setActiveColor(color.name)}
                title={color.label}
              />
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default ThemeBuilder;
